export const projs = [
    {
      'img': '/alt.png',
      'title': 'MediHealth',
      'slug': 'medihealth',
      'desc': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque odio velit provident nobis, animi porro optio aspernatur amet temporibus non.',
      'overview': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'role': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'my-impact': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'tags': ['Flutter', 'Dart', 'Figma', 'UI/UX Design'],
      'github': 'https://github.com/adviti-mishra/MediHealth'},
    {
      'img': '/alt.png',
      'title': 'Personal Website',
      'slug': 'personal-website',
      'desc': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque odio velit provident nobis, animi porro optio aspernatur amet temporibus non.',
      'overview': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'role': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'my-impact': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'tags': ['Next.JS', 'TailwindCSS', 'Typescript', 'Figma', 'UI/UX Design'],
      'github': 'https://github.com/j0hnxie/Personal-Website',
      'link': '/',
    },
    {
      'img': '/alt.png',
      'title': 'Ultima Insights',
      'slug': 'ultima-insights',
      'desc': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque odio velit provident nobis, animi porro optio aspernatur amet temporibus non.',
      'overview': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'role': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'my-impact': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'tags': ['Next.JS', 'TailwindCSS', 'Typescript', 'Javascript', 'API'],
      'link': 'https://beta.ultimainsights.ai/',
    },
    {
      'img': '/alt.png',
      'title': 'clDice Research',
      'slug': 'clDice-research',
      'desc': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque odio velit provident nobis, animi porro optio aspernatur amet temporibus non.',
      'overview': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'role': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'my-impact': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'tags': ['Python', 'PyTorch', 'Pandas'],
      'github': 'https://github.com/j0hnxie/clDice-Research',
      'paper': 'https://drive.google.com/file/d/1ey9PmD2WCk0mc4XHeJdUEe9Squ9-p2WR/view?usp=sharing',
    },
    {
      'img': '/alt.png',
      'title': 'Mentaro Startup',
      'slug': 'mentaro',
      'overview': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'role': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'my-impact': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'desc': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque odio velit provident nobis, animi porro optio aspernatur amet temporibus non.',
      'tags': ['React.JS', 'Python', 'PostgreSQL', 'Flask'],
      'github': 'https://github.com/j0hnxie/Mentaro-Early-Draft-',
    },
    {
      'img': '/alt.png',
      'title': 'Usability Study',
      'slug': 'usability-study',
      'overview': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'role': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'my-impact': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'desc': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque odio velit provident nobis, animi porro optio aspernatur amet temporibus non.',
      'tags': ['UI/UX Principles', 'UI/UX Design'],
      'paper': 'https://drive.google.com/file/d/1b4F-Inxwj_bHB_HGvQ8TsFO4JCpobb02/view',
    },
    {
      'img': '/alt.png',
      'title': 'Fake News Detector',
      'slug': 'fake-news',
      'overview': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'role': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'my-impact': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio incidunt recusandae quibusdam inventore dolorem voluptates? Laudantium voluptatibus molestias quam saepe quis ducimus quaerat necessitatibus quas natus sint maxime quod esse nulla tenetur dicta ullam suscipit, eos explicabo nam animi. Odit vel voluptates obcaecati earum amet repellendus accusamus, in magnam facilis!',
      'desc': 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque odio velit provident nobis, animi porro optio aspernatur amet temporibus non.',
      'tags': ['Python', 'sklearn', 'Pandas'],
      'paper': 'https://drive.google.com/file/d/1ACg2iJ0Vx2ODyGZT4J0GefKqNHnjAhlG/view',
    }
  ]